#!/usr/bin/env python3
"""Generate test/sql/trigrams_fixtures.test from a Python reference implementation.

The reference mirrors the extension's normalization contract: per-codepoint simple
lowercase, then a sliding window of gram_size codepoints. utf8proc (used by the
extension) applies simple 1:1 case mappings; Python's str.lower() applies full
mappings, which agree with simple mappings whenever the result is a single
codepoint and the character is folded in isolation (no final-sigma context).
Fixtures are restricted to codepoints where both agree; folding characters one at
a time keeps Python from applying context-sensitive mappings.

Run from the repo root:  python3 scripts/gen_trigram_fixtures.py
"""

import os

FIXTURES = [
    "Hello, World!",
    "DuckDB NGRAM Index",
    "ÀÉÎÕÜ àéîõü",
    "ΛΟΓΟΣ σοφία",
    "ПРИВЕТ мир",
    "日本語のテキスト",
    "naïve café résumé",
    "a🦆b🦆c",
    "éclair",  # combining acute: é as two codepoints
    "ẞôΩ mixed ЩЕДРІСТЬ",
    "tent often entered",
    "MIXEDcase123!@#",
    "abc",
    "ab",
    "",
]

CONFIGS = [
    (3, True),
    (3, False),
    (2, True),
    (4, True),
]


def fold_codepoint(ch: str) -> str:
    low = ch.lower()
    if len(low) != 1:
        raise ValueError(f"fixture uses {ch!r}, whose full lowercase {low!r} diverges from simple mapping")
    return low


def reference_grams(s: str, gram_size: int, case_insensitive: bool) -> list:
    cps = [fold_codepoint(ch) for ch in s] if case_insensitive else list(s)
    return ["".join(cps[i : i + gram_size]) for i in range(len(cps) - gram_size + 1)]


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    out_path = os.path.join(os.path.dirname(__file__), "..", "test", "sql", "trigrams_fixtures.test")
    lines = [
        "# name: test/sql/trigrams_fixtures.test",
        "# description: trigrams() vs Python reference implementation on unicode fixtures",
        "# group: [sql]",
        "",
        "# GENERATED by scripts/gen_trigram_fixtures.py -- edit and rerun that script instead.",
        "",
        "require ngram",
    ]
    for text in FIXTURES:
        for gram_size, case_insensitive in CONFIGS:
            expected = reference_grams(text, gram_size, case_insensitive)
            if any("\t" in g or "\n" in g for g in expected):
                raise ValueError("fixtures must not produce tabs or newlines")
            ci_sql = "true" if case_insensitive else "false"
            lines.append("")
            lines.append("query I")
            lines.append(f"SELECT unnest(trigrams({sql_quote(text)}, {gram_size}, {ci_sql}));")
            lines.append("----")
            lines.extend(expected)
    with open(out_path, "w", encoding="utf8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.normpath(out_path)}")


if __name__ == "__main__":
    main()
